### ISSUE TITLE
Requirements unclear

### ISSUE THREAD

**Issue by ghost** [aimaat/RemoteUpdate#2]
Ah finally what I was looking for! Thank you!

Before I run in I have some doubts.

Oldest server we are using is Windows Server 2012 R2
Your requirements says:
```
Windows Server 2012 or newer
Powershell 5
```
Windows Server 2012 R2 does have Powershell 4.0.
What does that mean?

```therefore the tool uses a little workaround with a Powershell VirtualAccount.```
Can you explain a bit further what that means and what it does? What is special about it? Do I have to create it?

```RemoteUpdate uses the Powershell Module PSWindowsUpdate to install Windows Updates```
Thats how I got here. What happens when it is not installed? Will it be installed automatically? If so is there a way to prevent that?

Thanks you for this very handy tool!

**Comment by ghost** [comment]
Under Application settings. What does "PS WU Commands" mean?

**Comment by aimaat** [comment]
Hi,

thanks for the appreciation.

For Powershell 5 on Windows Server 2012 you have to install the WMF5.1
https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/wmf/setup/install-configure?view=powershell-5.1

The "VirtualAccount" is basically a flag for the New-PSSessionConfigurationFile commandlet that grants the possibility to run commands with full admin rights.
You can find more about this here:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-pssessionconfiguration?view=powershell-5.1
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssessionconfigurationfile?view=powershell-5.1

And no, you don't have to do anything, i'm creating it automatically with the Name you choose in the settings (Default "VirtualAccount"), the same for the PSWindowsUpdate Module.
i try to download it if there is a internet connection, if not you are getting an error (verbose output also in the log file) and you would have to install it manualy on the remote hosts. But there is no option that will stop the automatic deployment from the module.

The PS WU commands are for special tags you want to send to PSWindowsUpdate like -MicrosoftUpdate
With this you can override the system settings and not use the configured WSUS and use the MicrosoftUpdate directly.
Or "-NotTitle Silverlight" if you want to exclude every update that contains silverlight in the title.
But thats all a part from PSWindowsUpdate that i'm just using --> http://woshub.com/pswindowsupdate-module/

Regards
