### ISSUE TITLE
Scrollbar und Import

### ISSUE THREAD

**Issue by aalbng** [aimaat/RemoteUpdate#5]
Hallo,

erstmal danke für das praktische Tool. Leider habe ich gerade das Problem das die Liste ein bisschen länger wäre als der Bildschirm. Hier wäre es schön wenn man ab x-Einträgen eine Scrollbar hätte.

Zusätzlich wäre noch eine Funktion nützlich wenn man viele Hosts und Credentials hat diese über eine TEXT/CSV/XML importieren oder exportieren zu können.

**Comment by aimaat** [comment]
Hi,

sorry für die späte Rückmeldung. Scrollbar ist leider mit dem von mir verwendeten Aufbau, zumindest für mich, nicht so leicht. Müsste sich jemand mit mehr Designerfahrung anschauen wie und ob man das leicht hinzufügen kann. Ausweg war bisher immer das ganze in einen zweiten Ordner zu legen und nochmals zu öffnen, dann kann man zwei unterschiedliche Listen führen.

Bezüglich Import gibt es ja grundsätzlich die Möglichkeit die vorhandenen Daten in ein XML im verwendeten Format und im selben Ordner zu speichern, dann wird das ja beim Start geladen (Credentials gehen halt nicht ohne Mühe von außen). Ein extra Import ist aktuell ansonsten einmal nicht vorgesehen.
