### ISSUE TITLE
RemoteUpdate_1_TemporaryKey.pfx not found

### ISSUE THREAD

**Issue by taksis** [aimaat/RemoteUpdate#7]
File `<ManifestKeyFile>RemoteUpdate_1_TemporaryKey.pfx</ManifestKeyFile>` referenced in project file RemoteUpdate\RemoteUpdate.csproj is not found.

**Comment by aimaat** [comment]
i've removed the manifest signing, so now your error should disappear. (but you could always create your own certificate for signing)
